### ISSUE TITLE
move commonly used iPython notebooks to dms_tools

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/dms_tools#11]
@mbdoud and @orrzor have a number of commonly used functions that they define in their `iPython` notebooks. Moving these into `dms_tools` so that they are accessible via the Python API would be better programming practice. Functions that are repeatedly re-used in different analyses are better incorporated as part of a software package. And the `iPython` notebooks would be simpler to read if they focused on the actual analysis at hand rather than spending huge amounts of text defining general functions. 

Specific functions that seem like good candidates (looking here: https://github.com/jbloomlab/WSN-HA_mAb_dms/blob/master/SecondaryAnalysis_all_mAbs/SecondaryAnalysis_all_mAbs.ipynb):
1. `ReadCodonCountsToAA` : note that this function to be a compound of the existing `ReadCodonCounts` and `SumCodonToAA`, and so perhaps could be re-written as such?
2. `ReadCodonCountsToAA_DataFrame`: maybe you could just make `ReadCodonCountsToAA` have an option to return either a dictionary or data frame rather than having two separate functions?
3. `ParseNSMutFreqBySite`
4. I think the correlation plots should be made part of `dms_correlate`, so actually part of the script, not just the Python API. This seems like a general action: to correlate the differential selection values.
5. Perhaps some other functions, I haven't looked carefully.

Let me know if there are specific parts of this that one of you wants to work on, or specific parts that you want me to do.

**Comment by mbdoud** [comment]
I'm happy to work on 1-4.  Furthermore I think @orrzor's functions `MeanMutDiffSel` (which doesn't seem to exist anywhere in `dms_tools` as far as I know) and `MutDiffSelToSiteDiffSel` (which already exists in some form in `dms_diffselection`, but might be good in the API and should be used automatically when calling `dms_merge` on diffselection files) are super useful and probably should be a standard part of the `dms_merge` script.

**Comment by jbloom** [comment]
OK, sounds good.

**Comment by jbloom** [comment]
I am moving @orrzor  `MeanMutDiffSel` and `MutDiffSelToSiteDiffSel` functions into `dms_merge` right now, and will update when this is done.

**Comment by jbloom** [comment]
@mbdoud @orrzor: I moved Orr's `MeanMutDiffSel` and `MutDiffSelToSiteDiffSel` operations into things that can be be performed using `dms_merge`.

@mbdoud: Do you want to do the other stuff in this issue now?

**Comment by mbdoud** [comment]
OK, will do.

**Comment by mbdoud** [comment]
Items 1 and 2 above have been incorporated into `dms_tools.file_io.ReadDMSCounts()` in bcf524129881c64b299abd9bcc7559d8e9cc867a.

**Comment by mbdoud** [comment]
Item 3 added in db642d4b0573592422ae58c6147fe725cbd11650. It isn't formulated exactly the same way as my original function (it takes a counts file instead of a counts dictionary and the returned 2-tuple is structured a little differently) but I think this is better in general.

**Comment by mbdoud** [comment]
Item 4 added in 9f9a78b10880339b71d938a4d5e82dee2f5a1537.
