### ISSUE TITLE
division by 0 in ReadDMSCounts

### ISSUE THREAD

**Issue by orrzor** [jbloomlab/dms_tools#12]
In _ReadDMSCounts_, there is now functionality to calculate character frequencies. For the line, `counts[site]['F_%s' % c] = float(counts[site][c])/counts[site]['COUNTS']`, there should probably be a catch for when the site has zero counts and division by 0 occurs? 

I sometimes use _WriteDMSCounts_ to write count files where not all sites have counts. For instance in the targeted amplicon sequencing, only a region of NP has been sequenced and is assigned counts. All sites outside the amplicon have counts 0. Now when that gets read by _ReadDMSCounts_, there is division by 0. I think it would be good to catch the division by 0 error and then assign a 0 frequency for the characters at that site.

**Comment by jbloom** [comment]
@orrzor: Yes, this is a good point. I would suggest adding that check. Decide what to assign 'F_x' when the counts are zero. I would suggest probably _float('NaN')_, although I suppose zero would also be an option. Can you make this change? Also update docs for function to explain how this case is handled.

**Comment by orrzor** [comment]
I added a try/except clause to catch the ZeroDivisionError and assigned float('NaN') as the frequency. I added a sentence explaining this in the _ReadDMSCounts_ function doc.
