### ISSUE TITLE
Remove suggestion to use `sudo` with `pip`

### ISSUE THREAD

**Issue by altendky** [jbloomlab/dms_tools#14]
http://jbloomlab.github.io/dms_tools/installation.html#quick-installation

Using `sudo` with `pip` is a bad because it mixes system package management with pip package management.  People frequently end up in `#python` with totally busted Python installs because of this.  Please remove the suggestion from the docs.

**Comment by jbloom** [comment]
Thanks for pointing this out, I'll make the change shortly when I push the next version of the docs.

**Comment by jbloom** [comment]
Installation instructions have been updated:
http://jbloomlab.github.io/dms_tools/installation.html

**Comment by altendky** [comment]
Thanks for getting this changed, I appreciate it.

But, I don't particularly agree with the argument provided in the link since sudo running stuff as root is pretty much it's purpose.  The reason not to sudo with pip is that in most cases the system python packages are managed by the system package manager.  Mixing the system package manager with pip means that you have two separate managers working in the same area.  This tends to cause trouble.

**Comment by jbloom** [comment]
Do you have a link that describes that argument? If so I can link to it as explanation.

**Comment by altendky** [comment]
Sadly the explanation with only six votes on your linked question is right on...  but, I'm asking in #python if we have a preferred link for this.  I'll let you know if something comes up.
