### ISSUE TITLE
MCMC FAILED to converge after all attempts

### ISSUE THREAD

**Issue by rraadd88** [jbloomlab/dms_tools#15]
I get this error while running dms_tools to analyze DMS data from [Olson et al](http://www.cell.com/current-biology/abstract/S0960-9822(14)01268-8).
There are no errors for any other datasets that I have analysed with dms_tools (version: 1.1.15).
I am not sure why this is happening for this particular data.
Please have a look at the logfile if you can find anything.

Logfile: https://github.com/rraadd88/tests/blob/master/Selection_WRT_Input.log
Command used: `python dms_inferprefs Input Selection --ncpus -10 --chartype aa`
Input counts: https://github.com/rraadd88/tests/blob/master/Input
Selection counts: https://github.com/rraadd88/tests/blob/master/Selection

**Comment by jbloom** [comment]
@rraadd88: Thanks for pointing this out. I reproduced the problem by running this on my computer, although the failure in my case was for a different site.

So there is definitely something with this dataset that is causing things to fail. One notable feature of this dataset is that the frequency of mutations at any given site seems very high. For instance, in most datasets I've analyzed, the frequency of any given mutation at a site is << 1%. Here the mutations are often at >1%.

As a short-term solution, you can run with the `--ratio_estimation` option and get what are probably reasonable results.

The attached `run` script in the ZIP does this. First, I converted your count files to having integers, then I ran things with ratio estimation.

Has the `dms_tools` usually worked OK for you on other datasets without crashing in this way?

[Rohan.zip](https://github.com/jbloomlab/dms_tools/files/758752/Rohan.zip)

**Comment by rraadd88** [comment]
Other data with floats seemed to have worked OK without crashing.
But if I correlate the inferences obtained from integer and float counts, there is a minor difference (correlation.pdf,correlation_diff.pdf).
I guess I should be using integers then.

Other data: BTEM1 (from Firnberg et al): [ZIP](https://github.com/jbloomlab/dms_tools/files/763889/integers_vs_floats.zip)
Note that files with integer counts have a '2' suffix.

**Comment by jbloom** [comment]
@rraadd88: OK, looks like the differences between integers and floats are sufficiently minor that we shouldn't worry about this. The values are very slightly different, but these differences are tiny compared to actual values.

Sorry that I don't have an answer for why things are failing on the protein G dataset, but hopefully the `--ratio_estimation` option is an OK substitute for now. Please let me know if you get similar errors for any future datasets.
