### ISSUE TITLE
Equations not rendered on some docs pages

### ISSUE THREAD

**Issue by skhilton** [jbloomlab/dms_tools#17]
Some of the equations, such as 11-16 and 18 on the `nferprefs_algorithm`, are not rendering correctly on the webpage. 

I believe these equations are duplicated on `nferdiffprefs_algorithm` page as they also do not render there.

**Comment by jbloom** [comment]
Fixed with this commit:
https://github.com/jbloomlab/dms_tools/commit/5b2ba14ce3b763fc0633eb8f5f92110acaff6710
