### ISSUE TITLE
Bar plots misaligned

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/dms_tools#18]
Barplots generated by`dms_summarizealignments` have a problem where the ticks are not properly aligned with the bars. Instead of being aligned in the center of the bar, they are aligned at the right-hand side of the bar.

**Comment by Haddox** [comment]
Here is an example

![image](https://user-images.githubusercontent.com/4372993/28145889-a2002554-672a-11e7-8e3b-b81f6cfa0661.png)

**Comment by jbloom** [comment]
@Haddox: I'm actually thinking of trying for a fairly major re-write of `dms_tools` soon, so I'll keep this in mind as one of many things to fix then. In the meantime, you can try to fix it, it should be some pretty easy option to the plotting command.

Alternatively, it's probably OK for `Jupyter` notebooks and the like, and we can manually move the labels if we need any publication-quality figures.

**Comment by jbloom** [comment]
This is not a problem if you use [dms_tools2](https://jbloomlab.github.io/dms_tools2/) instead.
