### ISSUE TITLE
ratio estimation

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/dms_tools#2]
@haddox I looked at your updates to the preferences estimates from enrichment ratios. Your changes look good. 

I have just made a few stylistic tweaks to the code by moving some items out of a for loop that didn't need to be executed each time.

You can see the changes using `git diff`. First pull the repository. Then type `git log`. You will see that your most recent commit was `6d113ebf9513c09d08629e15db8dd645af87da94`, and my last one was `9de5d5af0cb55f9d6badb466064eeb15f12f36e1`. So you can see the changes I made to the code in `src/mcmc/py` by typing:

```
git diff 6d113ebf9513c09d08629e15db8dd645af87da94 9de5d5af0cb55f9d6badb466064eeb15f12f36e1 src/mcmc.py
```

After reviewing these changes, the last thing we need to do is update the documentation for `dms_inferprefs` to explain how the enrichment ratios are now calculated. This is currently done for the `src/mcmc.py` file, but not in `docs/dms_inferprefs.rst`. So update this documentation to reflect the corrected approach, building the docs with:

```
 cd docs
 make html
```

and then looking in `docs/_build/html/dms_inferprefs.html` for the updated documentation.

After you've made these changes, you can push them back and I'll look at them. 

Also, look into what you think needs to be done for the differential preferences estimation...

**Comment by Haddox** [comment]
I just pushed files that have updated documentation and code for inferring preferences and differential preferences by enrichment ratios. I incorporated doctest code as an initial test that the new algorithm for inferring differential preferences is working as expected.

**Comment by jbloom** [comment]
@haddox Your changes look good. I incremented to version 1.1.8 and pushed the updated program to PyPI and the updated documentation to GitHub pages. So check the online documentation to make sure it looks OK to you, and then close this issue.

**Comment by Haddox** [comment]
@jbloom I made a minor change to the documentation and have pushed my changes. But otherwise everything looks good to me. I'll close the issue.
