### ISSUE TITLE
Determining whether a mutation is beneficial, deleterious or neutral

### ISSUE THREAD

**Issue by rraadd88** [jbloomlab/dms_tools#8]
Hi,
I am trying to analyse DMS data of TEM1 from Firnberg et. al. 2014 (A Comprehensive .. Gene’s Fitness Landscape) which is available [here](http://mbe.oxfordjournals.org/content/suppl/2014/02/22/msu081.DC1/Data_S1-S4.xlsx).
For that, I converted sequencing counts data to the input format used for _dms_tools_ as described in case of Melnikov et al. [example](https://github.com/jbloom/dms_tools/tree/master/examples/Melnikov_et_al_Tn5).

I got the preferences for each site by following command,

```
python dms_inferprefs Amp0.5.mat_mut_aas_X Amp256.mat_mut_aas_X Amp256_inferprefs_X.txt --ncpus -1 --chartype aa
```

The distribution of preferences looks like this,

![dist](https://github.com/rraadd88/aaprogs_testing/blob/master/dms_tools/output/Amp256_inferprefs_X.dist.png?raw=true)

So to infer whether a mutation is beneficial/deleterious in case of ratio based approach, it's very clear (>1 or <1). I went through the manuscript and the documentation but I could not find out how to do it with the preferences values.
Please let me know.

inputs (sequencing counts) : https://github.com/rraadd88/aaprogs_testing/tree/master/dms_tools/input
outputs (preferences) : https://github.com/rraadd88/aaprogs_testing/tree/master/dms_tools/output

**Comment by jbloom** [comment]
For any given mutation, just take the ratio of the preferences. E.g., for site `r` if the wildtype residue is `x` and you want the effect of mutation to `y`, do `\pi_{r,y} / \pi_{r,x}` where `\pi_{r,a}` is the preference for residue `a` at position `r`. If this ratio is > 1, the mutation is favorable. If it is less than 1, the mutation is unfavorable.

By the way, I think the Stiffler and Ranganathan paper (http://www.ncbi.nlm.nih.gov/pubmed/25723163) has higher-quality lactamase data than the Firnberg et al paper, particularly if you take the Stiffler values for the highest antibiotic concentration.

**Comment by rraadd88** [comment]
I did as you said and the distribution of `\pi_{r,y} / \pi_{r,x}` looks like this.
![dist](https://github.com/rraadd88/aaprogs_testing/blob/master/dms_tools/output/Amp256_inferprefs_X.dist_FiAsite_wrt_FiW.png?raw=true)

 `\pi_{r,y} / \pi_{r,x}` along the positions in the reference sequence, 
In red, blue and gray are beneficial, deleterious mutations and wild type resp. 

![pos](https://github.com/rraadd88/aaprogs_testing/blob/master/dms_tools/output/Amp256_inferprefs_X.pos_FiAsite_wrt_FiW.png?raw=true)

Yes, Stiffler et. al.'s data seems to be more comprehensive but unfortunately counts for synonymous mutations which I need are [not available](http://www.cell.com/cms/attachment/2041934527/2055315328/mmc1.xlsx) (even though their library is cloned with NNS primers strategy).

Thanks.

**Comment by jbloom** [comment]
OK, these look like reasonably sensible results -- right?

**Comment by rraadd88** [comment]
Yes. thanks.
